### PR TITLE
Various minor developer life improvements

### PR DESCRIPTION
**Pull request by ceball**
Various miscellaneous improvements.

Potentially controversial changes:
  * Makefile: Make default python and pip be "python" and "pip" rather than "python3.7" and "pip3" as I believe the former is more common. (The uncommon case is available via `make PYTHON=python3.7 PIP=pip3 ...`.)
  * Remove instruction to install from source with `setup.py install` from README. Explanation:
    * People who know about `setup.py install` don't need to be told about it, and everyone else doesn't need to know about it (at least, that's what I think - people installing from source don't need instructions, they'll do whatever they want/normally do...)
    * `pip install .` is what's in the Makefile anyway for `make install`.

Large but hopefully inconsequential change:
  * Azure: Refactor to use a template, and move azure files into `.azure`. Should be no change except for deliberate dropping of the "which python" stage on windows. Could be restored if it's necessary.

Minor changes:
  * Add missing description to package.json.
  * Remove outdated requirements.txt from MANIFEST.in
  * Minor name fixes from moving tests into package in the past.
  * Makefile: Allow different python/pip to be specified.
  * Makefile: Add target to verify all the bits are present and active. (With a horrible hack for checking the serverextension.)
  * Azure: Install/activate the extensions, and check that all worked out.

  Screenshot from 2020-04-30 22-59-26

### CODE REVIEW

**Comment by ceball** [comment]
@timkpaine looks like the displayed status of the checks should be ignored, as the checks passed for the most recent commit:

Screenshot from 2020-05-01 08-02-11

(unless I'm confused)

It's worth agreeing that all the changes in here are acceptable; I don't mind adjusting some bits back to how they were before.

**Comment by timkpaine** [comment]
@ceball im ok with most of this, are you set on the azure template? My only hesitation is I hate how all these repos end up with so many files in the top level, and we're adding another.

**Comment by ceball** [comment]
### Short story

New proposal: change `azure-pipelines.yml` to `.azure/pipelines.yml` and pick that as the pipeline settings file. Then there is only `.azure` at the top level, but we still get the reduction in duplicate jobs definitions and line count. What do you think? (If you have other problems with the template too - e.g. complexity - that is a different matter...)

### Long story

> are you set on the azure template? My only hesitation is I hate how all these repos end up with so many files in the top level, and we're adding another.

Tell me about it, ha ha. I still remember the days when repos had more code files relevant to the problem the project was solving than other files :) 

Having said that, the change removes a bunch of duplicate job definitions, and 100 lines of azure yml, so I am somewhat keen to keep that win.

Because I also do not like more files at the top level, originally I tried to look to see if the azure pipeline file could be moved, but I couldn't see how. I also tried to use yml anchors and references within a single `azure-pipelines.yml` file instead of adding a new file, but such yml features are explicitly disallowed by azure (not a crazy thing to do, given the complexity they can introduce).

However, I just clicked around harder on azure until eventually I found this:

af

Looks to me like if I were to move the file inside `.azure`, I could select it here. But I am not 100% certain about that - would need to try.

Anyway, if we do decide on an approach here that reduces line count/duplication, the benefit could be multiplied by applying it across a number of similar repos. 

(Though it would be even better if you could share stuff like azure templates across repos...particularly since such stuff will never be run locally and just refers to generic/common Makefile targets. Maybe if your stuff is complicated enough, you create a github action, which you and others can then re-use across projects - not sure as I haven't evaluated actions yet.)

**Comment by ceball** [comment]
Ha ha, I also remember the days when you just focused on your code, and if it didn't work for others, that was their problem rather than your problem - CI is so annoying :)

**Comment by timkpaine** [comment]
@ceball I like moving it all to `.azure`. I believe poetry is supposed to solve some of the problems with top level python files, I think we can configure .readthedocs directly in read the docs settings, and if we move the js to a sub folder we can replace 5 files and 2 folders with 1 `js` folder. for a later commit...

**Comment by ceball** [comment]
Ok, I set a different location for the azure pipeline file in the web UI, and that seems to have worked (all the checks passed, although the PR status is still confused - something I believe I've seen before with azure). 

I used `.azure` for the folder name as mentioned above, but began to wonder if it should be more generic, like `.ci` or whatever. We can change from `.azure` if someone has a strong opinion now or in the future.

@timkpaine I agree with your aim to remove more of the top-level files, and that it can happen in future/over time.

Note: If we don't merge this PR, need to revert the azure pipelines setting for the yml file, or else all builds will fail...

**Pull request merged**
